# Generated by Django 5.1.4 on 2025-01-06 21:26

import apps.minute.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("approval_chain", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MinuteApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_approver",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the user is the current approver in the chain.",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("approve", "Approve"),
                            ("reject", "Reject"),
                            ("mark-to", "Mark-To"),
                            ("return-to", "Return-To"),
                        ],
                        help_text="Action performed by the approver.",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True,
                        help_text="Optional remarks provided by the approver.",
                        null=True,
                    ),
                ),
                (
                    "action_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of when the approver performed the action.",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Submitted", "Submitted"),
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        help_text="Tracks the current status of the approval process.",
                        max_length=50,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when the approval record was created.",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the approval record was last updated.",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Minute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Title of the minute.", max_length=255),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True,
                        help_text="Optional subject of the minute.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the minute."),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        help_text="Optional file attachment for the minute.",
                        null=True,
                        upload_to="minutes/",
                        validators=[
                            apps.minute.models.validate_file_extension,
                            apps.minute.models.validate_file_size,
                        ],
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp of when the minute was created.",
                    ),
                ),
                (
                    "unique_id",
                    models.CharField(
                        blank=True,
                        editable=False,
                        help_text="Auto-generated unique ID for the minute.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Submitted", "Submitted"),
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Draft",
                        help_text="Current status of the minute.",
                        max_length=20,
                    ),
                ),
                (
                    "approval_chain",
                    models.OneToOneField(
                        blank=True,
                        help_text="Links the minute to its unique approval chain.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="minute",
                        to="approval_chain.approvalchain",
                    ),
                ),
            ],
        ),
    ]
