# Generated by Django 5.1.4 on 2025-01-06 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("approval_chain", "0002_initial"),
        ("minute", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="minute",
            name="created_by",
            field=models.ForeignKey(
                help_text="The user who created this minute.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="minutes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="minuteapproval",
            name="approval_chain",
            field=models.ForeignKey(
                help_text="The approval chain linked to this minute.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="minute_approvals",
                to="approval_chain.approvalchain",
            ),
        ),
        migrations.AddField(
            model_name="minuteapproval",
            name="approver",
            field=models.ForeignKey(
                help_text="The user responsible for reviewing the minute.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approvals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="minuteapproval",
            name="minute",
            field=models.ForeignKey(
                help_text="The minute document being tracked for approval.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approvals",
                to="minute.minute",
            ),
        ),
    ]
