# Generated by Django 5.1.4 on 2025-01-07 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("minute", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="minuteapproval",
            name="target_user",
            field=models.ForeignKey(
                blank=True,
                help_text="The user to whom this minute is marked (for mark-to action).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="marked_minutes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="minute",
            name="status",
            field=models.CharField(
                choices=[
                    ("Draft", "Draft"),
                    ("Submitted", "Submitted"),
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                    ("Marked", "Marked"),
                    ("Returned", "Returned"),
                ],
                default="Draft",
                help_text="Current status of the minute.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="minuteapproval",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                    ("Marked", "Marked"),
                    ("Returned", "Returned"),
                ],
                default="Pending",
                help_text="Tracks the current status of the approval process.",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="MinuteActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("approve", "Approve"),
                            ("reject", "Reject"),
                            ("mark-to", "Mark-To"),
                            ("return-to", "Return-To"),
                        ],
                        help_text="The action performed on the minute.",
                        max_length=20,
                    ),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True,
                        help_text="Optional remarks or comments associated with the action.",
                        null=True,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The time when the action was performed.",
                    ),
                ),
                (
                    "minute",
                    models.ForeignKey(
                        help_text="The minute document related to this log entry.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_logs",
                        to="minute.minute",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who performed the action.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performed_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="The target user for the action, if applicable (e.g., Mark-To, Return-To).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="targeted_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
