# Generated by Django 5.1.4 on 2025-01-08 07:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("minute", "0003_minuteapproval_target_user_alter_minute_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="minuteapproval",
            options={
                "verbose_name": "Minute Approval",
                "verbose_name_plural": "Minute Approvals",
            },
        ),
        migrations.AlterUniqueTogether(
            name="minuteapproval",
            unique_together={("minute", "approver")},
        ),
    ]
