# Generated by Django 5.1.4 on 2025-01-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("minute", "0004_alter_minuteapproval_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="minute",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp of the last update."
            ),
        ),
    ]
