# Generated by Django 5.1.4 on 2025-01-13 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approval_chain", "0004_approvalchain_minute"),
        ("minute", "0005_minute_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="minute",
            name="approval_chain",
            field=models.OneToOneField(
                blank=True,
                help_text="Links the minute to its unique approval chain.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="linked_minute",
                to="approval_chain.approvalchain",
            ),
        ),
    ]
