# Generated by Django 5.1.4 on 2025-01-14 06:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approval_chain", "0005_alter_approvalchain_minute"),
        ("minute", "0006_alter_minute_approval_chain"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="minuteactionlog",
            options={
                "verbose_name": "Minute Action Log",
                "verbose_name_plural": "Minute Action Logs",
            },
        ),
        migrations.AddIndex(
            model_name="minuteactionlog",
            index=models.Index(fields=["action"], name="action_idx"),
        ),
        migrations.AddIndex(
            model_name="minuteactionlog",
            index=models.Index(fields=["timestamp"], name="timestamp_idx"),
        ),
        migrations.AddConstraint(
            model_name="minuteapproval",
            constraint=models.UniqueConstraint(
                condition=models.Q(("current_approver", True)),
                fields=("minute",),
                name="unique_current_approver_per_minute",
            ),
        ),
    ]
