# Generated by Django 5.1.4 on 2025-01-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("minute", "0007_alter_minuteactionlog_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="minuteapproval",
            name="order",
            field=models.PositiveIntegerField(
                default=1, help_text="The sequence/order of the approver in the chain."
            ),
            preserve_default=False,
        ),
    ]
