# Generated by Django 5.1.4 on 2025-01-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("minute", "0008_minuteapproval_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="minuteapproval",
            name="order",
            field=models.PositiveIntegerField(
                help_text="Sequence/order of this approver in the approval chain."
            ),
        ),
    ]
