# Generated by Django 5.1.6 on 2025-02-11 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0003_department_dean"),
        ("minute", "0009_alter_minuteapproval_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="minute",
            name="archived",
            field=models.BooleanField(
                default=False,
                help_text="Marks the minute as archived after final approval.",
            ),
        ),
        migrations.AddField(
            model_name="minute",
            name="department",
            field=models.ForeignKey(
                help_text="The department this minute sheet belongs to.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="minutes",
                to="departments.department",
            ),
        ),
        migrations.AddField(
            model_name="minute",
            name="sheet_number",
            field=models.PositiveIntegerField(
                default=1, help_text="Sheet number for multi-page minute sheets."
            ),
        ),
        migrations.AlterField(
            model_name="minute",
            name="subject",
            field=models.TextField(
                default="Subject not provided", help_text="Subject of the minute sheet."
            ),
        ),
    ]
