# Generated by Django 5.1.4 on 2025-01-06 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={
                "verbose_name": "Department",
                "verbose_name_plural": "Departments",
            },
        ),
        migrations.AlterField(
            model_name="department",
            name="created_by",
            field=models.ForeignKey(
                help_text="User who created the department",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_departments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="department",
            constraint=models.UniqueConstraint(
                fields=("head_of_department",), name="unique_head_of_department"
            ),
        ),
    ]
