# Generated by Django 5.1.4 on 2025-01-20 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "departments",
            "0002_alter_department_options_alter_department_created_by_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="dean",
            field=models.ForeignKey(
                blank=True,
                help_text="User assigned as the Dean of the Department",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="dean_departments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
