# Generated by Django 5.1.4 on 2025-01-06 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApprovalChain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="A unique name for the approval chain.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The timestamp when this chain was created.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Completed", "Completed")],
                        default="Active",
                        help_text="The current status of the approval chain.",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Approval Chain",
                "verbose_name_plural": "Approval Chains",
            },
        ),
        migrations.CreateModel(
            name="Approver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        help_text="The sequence/order of this approver in the chain. Starts from 1."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                            ("Returned", "Returned"),
                        ],
                        default="Pending",
                        help_text="The current status of this approver's action.",
                        max_length=20,
                    ),
                ),
                (
                    "action_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="The timestamp when this approver took action.",
                        null=True,
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if this approver is the current active approver.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Approver",
                "verbose_name_plural": "Approvers",
                "ordering": ["order"],
            },
        ),
    ]
