# Generated by Django 5.1.4 on 2025-01-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approval_chain", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approver",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                    ("Marked", "Marked"),
                    ("Returned", "Returned"),
                ],
                default="Pending",
                help_text="The current status of this approver's action.",
                max_length=20,
            ),
        ),
    ]
