# Generated by Django 5.1.4 on 2025-01-13 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approval_chain", "0004_approvalchain_minute"),
        ("minute", "0006_alter_minute_approval_chain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="approvalchain",
            name="minute",
            field=models.OneToOneField(
                blank=True,
                help_text="The minute document linked to this approval chain.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="linked_approval_chain",
                to="minute.minute",
            ),
        ),
    ]
