# Generated by Django 5.1.4 on 2025-01-06 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        (
            "departments",
            "0002_alter_department_options_alter_department_created_by_and_more",
        ),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "verbose_name": "Custom User",
                "verbose_name_plural": "Custom Users",
            },
        ),
        # Add the 'department' field to CustomUser
        migrations.AddField(
            model_name="customuser",
            name="department",
            field=models.ForeignKey(
                blank=True,
                help_text="Department to which the user belongs.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="departments.department",
            ),
        ),
        # Add unique constraint on (username, role)
        migrations.AddConstraint(
            model_name="customuser",
            constraint=models.UniqueConstraint(
                fields=("username", "role"), name="unique_username_role"
            ),
        ),
    ]
