# Generated by Django 5.1.4 on 2025-01-07 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_customuser_departments_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="departments",
        ),
    ]
