# Generated by Django 5.1.4 on 2025-01-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    ("info", "Info"),
                    ("alert", "Alert"),
                    ("warning", "Warning"),
                    ("success", "Success"),
                ],
                default="info",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Optional expiration time for the notification.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="title",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="notification",
            name="link",
            field=models.URLField(
                blank=True, help_text="Optional link for the user to follow.", null=True
            ),
        ),
    ]
