# Generated by Django 5.1.4 on 2025-01-07 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "notifications",
            "0004_remove_notification_category_notification_type_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
            },
        ),
        migrations.AlterField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether the notification has been read by the user.",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Optional link to provide additional context or a call-to-action.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="message",
            field=models.TextField(
                help_text="Detailed message for the notification. Provide any necessary context."
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="title",
            field=models.CharField(
                help_text="Title of the notification. Keep it short and concise.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("info", "Info"),
                    ("success", "Success"),
                    ("warning", "Warning"),
                    ("error", "Error"),
                ],
                default="info",
                help_text="Type of notification to determine the priority and style.",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                help_text="The user to whom the notification is addressed.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
